name: Default

on: [push]

jobs:
  tests:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        php: [7.4, 7.3, 7.2]
        os: [ubuntu-latest, windows-latest]

    name: P${{ matrix.php }} - ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none

      - name: Run composer install
        run: composer install -n --prefer-dist
        env:
          APP_ENV: testing

      - name: Prepare Laravel Application
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Composer validate
        run: composer run self-validate

      - name: Run php code style fixer
        run: composer run phpcs

      - name: Run copy/paste detector
        run: composer run phpcpd

      - name: Run tests
        run: composer run phpunit

      - name: Upload artifacts
        uses: actions/upload-artifact@master
        if: failure()
        with:
          name: Logs
          path: ./storage/logs
